const Actions = {
    COUNTER_INCREMENT: 'INCREMENT',
    COUNTER_DECREMENT: 'DECREMENT',
    FETCH_POSTS: 'FETCH_POSTS',
    GOOGLE_LOGIN_SUCCESS: 'GOOGLE_LOGIN_SUCCESS',
    GOOGLE_LOGIN_FAILED: 'GOOGLE_LOGIN_FAILED',
    GOOGLE_LOGIN_ERROR: 'GOOGLE_LOGIN_ERROR',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    SET_DATE: 'SET_DATE',
    UPDATE_PROFILE: 'UPDATE_PROFILE'
}

export default Actions